// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMxExOCMIfJirY3lf3_xXDJX1m61T0lLQ',
    appId: '1:21582239855:web:a7b8acdcfe6e1c3790959a',
    messagingSenderId: '21582239855',
    projectId: 'learn-5634f',
    authDomain: 'learn-5634f.firebaseapp.com',
    storageBucket: 'learn-5634f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDO4JaXloU3axI2bMIDRo4PLh7tNptKSA',
    appId: '1:21582239855:android:d4c0b207c598987490959a',
    messagingSenderId: '21582239855',
    projectId: 'learn-5634f',
    storageBucket: 'learn-5634f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOmgm7KfXTdWC3Mcy2FA7y1YPymYwzRsc',
    appId: '1:21582239855:ios:f34482f45386d85490959a',
    messagingSenderId: '21582239855',
    projectId: 'learn-5634f',
    storageBucket: 'learn-5634f.appspot.com',
    iosClientId:
        '21582239855-2437gk668283jmdmna8pph7qrpagd7dv.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOmgm7KfXTdWC3Mcy2FA7y1YPymYwzRsc',
    appId: '1:21582239855:ios:f34482f45386d85490959a',
    messagingSenderId: '21582239855',
    projectId: 'learn-5634f',
    storageBucket: 'learn-5634f.appspot.com',
    iosClientId:
        '21582239855-2437gk668283jmdmna8pph7qrpagd7dv.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnApp',
  );
}
